
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Jan 25 2024 12:21:12 IST (Jan 25 2024 06:51:12 UTC)

// Verification Directory fv/fifo 

module fifo(clk, rst_n, w_en, r_en, data_in, data_out, full, empty);
  input clk, rst_n, w_en, r_en;
  input [7:0] data_in;
  output [7:0] data_out;
  output full, empty;
  wire clk, rst_n, w_en, r_en;
  wire [7:0] data_in;
  wire [7:0] data_out;
  wire full, empty;
  wire [3:0] r_ptr;
  wire [3:0] w_ptr;
  wire [7:0] \fifo[0] ;
  wire [7:0] \fifo[1] ;
  wire [7:0] \fifo[2] ;
  wire [7:0] \fifo[3] ;
  wire [7:0] \fifo[4] ;
  wire [7:0] \fifo[5] ;
  wire [7:0] \fifo[6] ;
  wire [7:0] \fifo[7] ;
  wire [7:0] \fifo[8] ;
  wire [7:0] \fifo[9] ;
  wire [7:0] \fifo[10] ;
  wire [7:0] \fifo[11] ;
  wire [7:0] \fifo[12] ;
  wire [7:0] \fifo[13] ;
  wire [7:0] \fifo[14] ;
  wire [7:0] \fifo[15] ;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_50, n_51, n_52, n_53, n_54, n_55, n_56;
  wire n_57, n_58, n_59, n_60, n_61, n_62, n_63, n_64;
  wire n_65, n_66, n_67, n_68, n_69, n_70, n_71, n_72;
  wire n_73, n_74, n_75, n_76, n_77, n_78, n_79, n_80;
  wire n_81, n_82, n_83, n_84, n_85, n_86, n_87, n_88;
  wire n_89, n_90, n_91, n_92, n_93, n_94, n_95, n_96;
  wire n_97, n_98, n_99, n_100, n_101, n_102, n_103, n_104;
  wire n_105, n_106, n_107, n_108, n_109, n_110, n_111, n_112;
  wire n_113, n_114, n_115, n_116, n_117, n_118, n_119, n_120;
  wire n_121, n_122, n_123, n_124, n_125, n_126, n_127, n_128;
  wire n_129, n_130, n_131, n_132, n_133, n_134, n_135, n_136;
  wire n_137, n_138, n_139, n_140, n_141, n_142, n_143, n_144;
  wire n_145, n_146, n_147, n_148, n_149, n_150, n_151, n_152;
  wire n_153, n_154, n_155, n_156, n_157, n_158, n_159, n_160;
  wire n_161, n_162, n_163, n_164, n_165, n_166, n_167, n_168;
  wire n_169, n_170, n_171, n_172, n_173, n_174, n_175, n_176;
  wire n_177, n_178, n_179, n_180, n_181, n_182, n_183, n_184;
  wire n_185, n_186, n_187, n_188, n_189, n_190, n_191, n_192;
  wire n_193, n_194, n_195, n_196, n_197, n_198, n_199, n_200;
  wire n_201, n_202, n_203, n_204, n_205, n_206, n_207, n_208;
  wire n_209, n_210, n_211, n_212, n_215, n_216, n_217, n_218;
  wire n_219, n_220, n_221, n_222, n_224, n_225, n_226, n_227;
  wire n_230;
  assign r_ptr[2] = 1'b0;
  assign w_ptr[1] = 1'b0;
  assign r_ptr[0] = 1'b0;
  assign w_ptr[0] = 1'b0;
  assign r_ptr[1] = 1'b0;
  assign w_ptr[2] = 1'b0;
  assign w_ptr[3] = 1'b0;
  assign r_ptr[3] = 1'b0;
  assign data_out[0] = 1'b0;
  assign data_out[1] = 1'b0;
  assign data_out[2] = 1'b0;
  assign data_out[3] = 1'b0;
  assign data_out[4] = 1'b0;
  assign data_out[5] = 1'b0;
  assign data_out[6] = 1'b0;
  assign data_out[7] = 1'b0;
  INVXL g1105(.A (n_230), .Y (empty));
  AND4X1 g1419(.A (n_212), .B (n_211), .C (n_222), .D (n_217), .Y
       (full));
  XNOR2X1 g1420(.A (n_224), .B (r_ptr[3]), .Y (n_222));
  XNOR2X1 g1421(.A (n_221), .B (w_ptr[3]), .Y (n_224));
  NAND3BXL g1424(.AN (n_219), .B (n_220), .C (n_218), .Y (n_230));
  XNOR2X1 g1426(.A (n_216), .B (w_ptr[2]), .Y (n_225));
  NAND2BXL g1427(.AN (n_216), .B (w_ptr[2]), .Y (n_221));
  AOI221XL g1429(.A0 (w_ptr[3]), .A1 (n_44), .B0 (n_46), .B1
       (r_ptr[3]), .C0 (n_210), .Y (n_220));
  XNOR2X1 g1430(.A (r_ptr[1]), .B (n_215), .Y (n_219));
  XNOR2X1 g1431(.A (w_ptr[0]), .B (n_215), .Y (n_226));
  CLKINVX4 g1432(.A (n_217), .Y (n_218));
  XNOR2X1 g1434(.A (r_ptr[0]), .B (n_227), .Y (n_217));
  NAND2BXL g1435(.AN (n_227), .B (w_ptr[1]), .Y (n_216));
  CLKINVX8 g1436(.A (w_ptr[1]), .Y (n_215));
  CLKINVX16 g1442(.A (w_ptr[0]), .Y (n_227));
  XNOR2X4 g2(.A (n_225), .B (r_ptr[2]), .Y (n_212));
  XNOR2X4 g1443(.A (n_226), .B (r_ptr[1]), .Y (n_211));
  XOR2X4 g1444(.A (r_ptr[2]), .B (w_ptr[2]), .Y (n_210));
  DFFHQX4 \data_out_reg[0]211 (.CK (clk), .D (n_208), .Q (data_out[0]));
  DFFHQX4 \data_out_reg[1]212 (.CK (clk), .D (n_206), .Q (data_out[1]));
  DFFHQX4 \data_out_reg[2]213 (.CK (clk), .D (n_204), .Q (data_out[2]));
  DFFHQX4 \data_out_reg[3]214 (.CK (clk), .D (n_207), .Q (data_out[3]));
  DFFHQX4 \data_out_reg[4]215 (.CK (clk), .D (n_209), .Q (data_out[4]));
  DFFHQX4 \data_out_reg[5]216 (.CK (clk), .D (n_203), .Q (data_out[5]));
  DFFHQX4 \data_out_reg[6]217 (.CK (clk), .D (n_205), .Q (data_out[6]));
  DFFHQX4 \data_out_reg[7]218 (.CK (clk), .D (n_202), .Q (data_out[7]));
  MDFFHQX4 \fifo_reg[0][0] (.CK (clk), .D0 (\fifo[0] [0]), .D1
       (data_in[0]), .S0 (n_122), .Q (\fifo[0] [0]));
  MDFFHQX4 \fifo_reg[0][1] (.CK (clk), .D0 (\fifo[0] [1]), .D1
       (data_in[1]), .S0 (n_122), .Q (\fifo[0] [1]));
  MDFFHQX4 \fifo_reg[0][2] (.CK (clk), .D0 (\fifo[0] [2]), .D1
       (data_in[2]), .S0 (n_122), .Q (\fifo[0] [2]));
  MDFFHQX4 \fifo_reg[0][3] (.CK (clk), .D0 (\fifo[0] [3]), .D1
       (data_in[3]), .S0 (n_122), .Q (\fifo[0] [3]));
  MDFFHQX4 \fifo_reg[0][4] (.CK (clk), .D0 (\fifo[0] [4]), .D1
       (data_in[4]), .S0 (n_122), .Q (\fifo[0] [4]));
  MDFFHQX4 \fifo_reg[0][5] (.CK (clk), .D0 (\fifo[0] [5]), .D1
       (data_in[5]), .S0 (n_122), .Q (\fifo[0] [5]));
  MDFFHQX4 \fifo_reg[0][6] (.CK (clk), .D0 (\fifo[0] [6]), .D1
       (data_in[6]), .S0 (n_122), .Q (\fifo[0] [6]));
  MDFFHQX4 \fifo_reg[0][7] (.CK (clk), .D0 (\fifo[0] [7]), .D1
       (data_in[7]), .S0 (n_122), .Q (\fifo[0] [7]));
  EDFFHQX8 \fifo_reg[1][0] (.CK (clk), .D (data_in[0]), .E (n_136), .Q
       (\fifo[1] [0]));
  EDFFHQX8 \fifo_reg[1][1] (.CK (clk), .D (data_in[1]), .E (n_136), .Q
       (\fifo[1] [1]));
  EDFFHQX8 \fifo_reg[1][3] (.CK (clk), .D (data_in[3]), .E (n_136), .Q
       (\fifo[1] [3]));
  EDFFHQX8 \fifo_reg[1][4] (.CK (clk), .D (data_in[4]), .E (n_136), .Q
       (\fifo[1] [4]));
  EDFFHQX8 \fifo_reg[1][5] (.CK (clk), .D (data_in[5]), .E (n_136), .Q
       (\fifo[1] [5]));
  EDFFHQX8 \fifo_reg[1][7] (.CK (clk), .D (data_in[7]), .E (n_136), .Q
       (\fifo[1] [7]));
  EDFFHQX8 \fifo_reg[2][0] (.CK (clk), .D (data_in[0]), .E (n_134), .Q
       (\fifo[2] [0]));
  EDFFHQX8 \fifo_reg[2][1] (.CK (clk), .D (data_in[1]), .E (n_134), .Q
       (\fifo[2] [1]));
  EDFFHQX8 \fifo_reg[2][3] (.CK (clk), .D (data_in[3]), .E (n_134), .Q
       (\fifo[2] [3]));
  EDFFHQX8 \fifo_reg[2][4] (.CK (clk), .D (data_in[4]), .E (n_134), .Q
       (\fifo[2] [4]));
  EDFFHQX8 \fifo_reg[2][5] (.CK (clk), .D (data_in[5]), .E (n_134), .Q
       (\fifo[2] [5]));
  EDFFHQX8 \fifo_reg[2][7] (.CK (clk), .D (data_in[7]), .E (n_134), .Q
       (\fifo[2] [7]));
  EDFFHQX8 \fifo_reg[3][0] (.CK (clk), .D (data_in[0]), .E (n_135), .Q
       (\fifo[3] [0]));
  EDFFHQX8 \fifo_reg[3][2] (.CK (clk), .D (data_in[2]), .E (n_135), .Q
       (\fifo[3] [2]));
  EDFFHQX8 \fifo_reg[3][5] (.CK (clk), .D (data_in[5]), .E (n_135), .Q
       (\fifo[3] [5]));
  EDFFHQX8 \fifo_reg[3][6] (.CK (clk), .D (data_in[6]), .E (n_135), .Q
       (\fifo[3] [6]));
  EDFFHQX8 \fifo_reg[4][0] (.CK (clk), .D (data_in[0]), .E (n_133), .Q
       (\fifo[4] [0]));
  EDFFHQX8 \fifo_reg[4][2] (.CK (clk), .D (data_in[2]), .E (n_133), .Q
       (\fifo[4] [2]));
  EDFFHQX8 \fifo_reg[4][5] (.CK (clk), .D (data_in[5]), .E (n_133), .Q
       (\fifo[4] [5]));
  EDFFHQX8 \fifo_reg[4][6] (.CK (clk), .D (data_in[6]), .E (n_133), .Q
       (\fifo[4] [6]));
  EDFFHQX8 \fifo_reg[5][0] (.CK (clk), .D (data_in[0]), .E (n_131), .Q
       (\fifo[5] [0]));
  EDFFHQX8 \fifo_reg[5][1] (.CK (clk), .D (data_in[1]), .E (n_131), .Q
       (\fifo[5] [1]));
  EDFFHQX8 \fifo_reg[5][2] (.CK (clk), .D (data_in[2]), .E (n_131), .Q
       (\fifo[5] [2]));
  EDFFHQX8 \fifo_reg[5][3] (.CK (clk), .D (data_in[3]), .E (n_131), .Q
       (\fifo[5] [3]));
  EDFFHQX8 \fifo_reg[5][4] (.CK (clk), .D (data_in[4]), .E (n_131), .Q
       (\fifo[5] [4]));
  EDFFHQX8 \fifo_reg[5][6] (.CK (clk), .D (data_in[6]), .E (n_131), .Q
       (\fifo[5] [6]));
  EDFFHQX8 \fifo_reg[5][7] (.CK (clk), .D (data_in[7]), .E (n_131), .Q
       (\fifo[5] [7]));
  EDFFHQX8 \fifo_reg[6][0] (.CK (clk), .D (data_in[0]), .E (n_129), .Q
       (\fifo[6] [0]));
  EDFFHQX8 \fifo_reg[6][1] (.CK (clk), .D (data_in[1]), .E (n_129), .Q
       (\fifo[6] [1]));
  EDFFHQX8 \fifo_reg[6][2] (.CK (clk), .D (data_in[2]), .E (n_129), .Q
       (\fifo[6] [2]));
  EDFFHQX8 \fifo_reg[6][3] (.CK (clk), .D (data_in[3]), .E (n_129), .Q
       (\fifo[6] [3]));
  EDFFHQX8 \fifo_reg[6][4] (.CK (clk), .D (data_in[4]), .E (n_129), .Q
       (\fifo[6] [4]));
  EDFFHQX8 \fifo_reg[6][6] (.CK (clk), .D (data_in[6]), .E (n_129), .Q
       (\fifo[6] [6]));
  EDFFHQX8 \fifo_reg[6][7] (.CK (clk), .D (data_in[7]), .E (n_129), .Q
       (\fifo[6] [7]));
  EDFFHQX8 \fifo_reg[7][0] (.CK (clk), .D (data_in[0]), .E (n_125), .Q
       (\fifo[7] [0]));
  EDFFHQX8 \fifo_reg[7][2] (.CK (clk), .D (data_in[2]), .E (n_125), .Q
       (\fifo[7] [2]));
  EDFFHQX8 \fifo_reg[7][4] (.CK (clk), .D (data_in[4]), .E (n_125), .Q
       (\fifo[7] [4]));
  EDFFHQX8 \fifo_reg[7][5] (.CK (clk), .D (data_in[5]), .E (n_125), .Q
       (\fifo[7] [5]));
  EDFFHQX8 \fifo_reg[7][7] (.CK (clk), .D (data_in[7]), .E (n_125), .Q
       (\fifo[7] [7]));
  EDFFHQX8 \fifo_reg[8][0] (.CK (clk), .D (data_in[0]), .E (n_130), .Q
       (\fifo[8] [0]));
  EDFFHQX8 \fifo_reg[8][2] (.CK (clk), .D (data_in[2]), .E (n_130), .Q
       (\fifo[8] [2]));
  EDFFHQX8 \fifo_reg[8][4] (.CK (clk), .D (data_in[4]), .E (n_130), .Q
       (\fifo[8] [4]));
  EDFFHQX8 \fifo_reg[8][5] (.CK (clk), .D (data_in[5]), .E (n_130), .Q
       (\fifo[8] [5]));
  EDFFHQX8 \fifo_reg[8][7] (.CK (clk), .D (data_in[7]), .E (n_130), .Q
       (\fifo[8] [7]));
  EDFFHQX8 \fifo_reg[9][1] (.CK (clk), .D (data_in[1]), .E (n_123), .Q
       (\fifo[9] [1]));
  EDFFHQX8 \fifo_reg[9][2] (.CK (clk), .D (data_in[2]), .E (n_123), .Q
       (\fifo[9] [2]));
  EDFFHQX8 \fifo_reg[9][3] (.CK (clk), .D (data_in[3]), .E (n_123), .Q
       (\fifo[9] [3]));
  EDFFHQX8 \fifo_reg[9][4] (.CK (clk), .D (data_in[4]), .E (n_123), .Q
       (\fifo[9] [4]));
  EDFFHQX8 \fifo_reg[9][6] (.CK (clk), .D (data_in[6]), .E (n_123), .Q
       (\fifo[9] [6]));
  EDFFHQX8 \fifo_reg[10][1] (.CK (clk), .D (data_in[1]), .E (n_126), .Q
       (\fifo[10] [1]));
  EDFFHQX8 \fifo_reg[10][2] (.CK (clk), .D (data_in[2]), .E (n_126), .Q
       (\fifo[10] [2]));
  EDFFHQX8 \fifo_reg[10][3] (.CK (clk), .D (data_in[3]), .E (n_126), .Q
       (\fifo[10] [3]));
  EDFFHQX8 \fifo_reg[10][4] (.CK (clk), .D (data_in[4]), .E (n_126), .Q
       (\fifo[10] [4]));
  EDFFHQX8 \fifo_reg[10][6] (.CK (clk), .D (data_in[6]), .E (n_126), .Q
       (\fifo[10] [6]));
  EDFFHQX8 \fifo_reg[11][0] (.CK (clk), .D (data_in[0]), .E (n_127), .Q
       (\fifo[11] [0]));
  EDFFHQX8 \fifo_reg[11][1] (.CK (clk), .D (data_in[1]), .E (n_127), .Q
       (\fifo[11] [1]));
  EDFFHQX8 \fifo_reg[11][2] (.CK (clk), .D (data_in[2]), .E (n_127), .Q
       (\fifo[11] [2]));
  EDFFHQX8 \fifo_reg[11][3] (.CK (clk), .D (data_in[3]), .E (n_127), .Q
       (\fifo[11] [3]));
  EDFFHQX8 \fifo_reg[11][4] (.CK (clk), .D (data_in[4]), .E (n_127), .Q
       (\fifo[11] [4]));
  EDFFHQX8 \fifo_reg[11][5] (.CK (clk), .D (data_in[5]), .E (n_127), .Q
       (\fifo[11] [5]));
  EDFFHQX8 \fifo_reg[11][6] (.CK (clk), .D (data_in[6]), .E (n_127), .Q
       (\fifo[11] [6]));
  EDFFHQX8 \fifo_reg[11][7] (.CK (clk), .D (data_in[7]), .E (n_127), .Q
       (\fifo[11] [7]));
  EDFFHQX8 \fifo_reg[12][0] (.CK (clk), .D (data_in[0]), .E (n_124), .Q
       (\fifo[12] [0]));
  EDFFHQX8 \fifo_reg[12][1] (.CK (clk), .D (data_in[1]), .E (n_124), .Q
       (\fifo[12] [1]));
  EDFFHQX8 \fifo_reg[12][2] (.CK (clk), .D (data_in[2]), .E (n_124), .Q
       (\fifo[12] [2]));
  EDFFHQX8 \fifo_reg[12][3] (.CK (clk), .D (data_in[3]), .E (n_124), .Q
       (\fifo[12] [3]));
  EDFFHQX8 \fifo_reg[12][4] (.CK (clk), .D (data_in[4]), .E (n_124), .Q
       (\fifo[12] [4]));
  EDFFHQX8 \fifo_reg[12][5] (.CK (clk), .D (data_in[5]), .E (n_124), .Q
       (\fifo[12] [5]));
  EDFFHQX8 \fifo_reg[12][6] (.CK (clk), .D (data_in[6]), .E (n_124), .Q
       (\fifo[12] [6]));
  EDFFHQX8 \fifo_reg[12][7] (.CK (clk), .D (data_in[7]), .E (n_124), .Q
       (\fifo[12] [7]));
  EDFFHQX8 \fifo_reg[13][0] (.CK (clk), .D (data_in[0]), .E (n_128), .Q
       (\fifo[13] [0]));
  EDFFHQX8 \fifo_reg[13][1] (.CK (clk), .D (data_in[1]), .E (n_128), .Q
       (\fifo[13] [1]));
  EDFFHQX8 \fifo_reg[13][3] (.CK (clk), .D (data_in[3]), .E (n_128), .Q
       (\fifo[13] [3]));
  EDFFHQX8 \fifo_reg[13][5] (.CK (clk), .D (data_in[5]), .E (n_128), .Q
       (\fifo[13] [5]));
  EDFFHQX8 \fifo_reg[13][6] (.CK (clk), .D (data_in[6]), .E (n_128), .Q
       (\fifo[13] [6]));
  EDFFHQX8 \fifo_reg[13][7] (.CK (clk), .D (data_in[7]), .E (n_128), .Q
       (\fifo[13] [7]));
  EDFFHQX8 \fifo_reg[14][0] (.CK (clk), .D (data_in[0]), .E (n_132), .Q
       (\fifo[14] [0]));
  EDFFHQX8 \fifo_reg[14][1] (.CK (clk), .D (data_in[1]), .E (n_132), .Q
       (\fifo[14] [1]));
  EDFFHQX8 \fifo_reg[14][3] (.CK (clk), .D (data_in[3]), .E (n_132), .Q
       (\fifo[14] [3]));
  EDFFHQX8 \fifo_reg[14][5] (.CK (clk), .D (data_in[5]), .E (n_132), .Q
       (\fifo[14] [5]));
  EDFFHQX8 \fifo_reg[14][6] (.CK (clk), .D (data_in[6]), .E (n_132), .Q
       (\fifo[14] [6]));
  EDFFHQX8 \fifo_reg[14][7] (.CK (clk), .D (data_in[7]), .E (n_132), .Q
       (\fifo[14] [7]));
  EDFFHQX8 \r_ptr_reg[0]227 (.CK (clk), .D (n_48), .E (n_0), .Q
       (r_ptr[0]));
  SMDFFHQX1 \r_ptr_reg[1]228 (.CK (clk), .D0 (r_ptr[1]), .D1 (n_43),
       .S0 (r_ptr[0]), .SE (n_62), .SI (r_ptr[1]), .Q (r_ptr[1]));
  EDFFHQX8 \r_ptr_reg[2]229 (.CK (clk), .D (n_87), .E (n_0), .Q
       (r_ptr[2]));
  SMDFFHQX1 \r_ptr_reg[3]230 (.CK (clk), .D0 (n_44), .D1 (r_ptr[3]),
       .S0 (n_76), .SE (n_62), .SI (r_ptr[3]), .Q (r_ptr[3]));
  EDFFHQX1 \w_ptr_reg[0]77 (.CK (clk), .D (n_227), .E (n_51), .Q
       (w_ptr[0]));
  EDFFHQX1 \w_ptr_reg[1]78 (.CK (clk), .D (n_226), .E (n_51), .Q
       (w_ptr[1]));
  EDFFHQX1 \w_ptr_reg[2]79 (.CK (clk), .D (n_225), .E (n_51), .Q
       (w_ptr[2]));
  EDFFHQX1 \w_ptr_reg[3]80 (.CK (clk), .D (n_224), .E (n_51), .Q
       (w_ptr[3]));
  OAI211XL g6273(.A0 (n_93), .A1 (n_33), .B0 (n_196), .C0 (n_198), .Y
       (n_209));
  OAI211XL g6274(.A0 (n_93), .A1 (n_14), .B0 (n_189), .C0 (n_190), .Y
       (n_208));
  OAI211XL g6275(.A0 (n_93), .A1 (n_27), .B0 (n_199), .C0 (n_200), .Y
       (n_207));
  OAI211XL g6276(.A0 (n_93), .A1 (n_28), .B0 (n_193), .C0 (n_201), .Y
       (n_206));
  OAI211XL g6277(.A0 (n_93), .A1 (n_29), .B0 (n_191), .C0 (n_186), .Y
       (n_205));
  OAI211XL g6278(.A0 (n_93), .A1 (n_23), .B0 (n_187), .C0 (n_192), .Y
       (n_204));
  OAI211XL g6279(.A0 (n_93), .A1 (n_36), .B0 (n_197), .C0 (n_195), .Y
       (n_203));
  OAI211XL g6280(.A0 (n_93), .A1 (n_40), .B0 (n_194), .C0 (n_188), .Y
       (n_202));
  AOI221XL g6281(.A0 (\fifo[1] [1]), .A1 (n_113), .B0 (n_116), .B1
       (\fifo[2] [1]), .C0 (n_179), .Y (n_201));
  AOI221XL g6282(.A0 (\fifo[1] [3]), .A1 (n_113), .B0 (n_116), .B1
       (\fifo[2] [3]), .C0 (n_184), .Y (n_200));
  AOI221XL g6283(.A0 (\fifo[13] [3]), .A1 (n_101), .B0 (n_103), .B1
       (\fifo[14] [3]), .C0 (n_183), .Y (n_199));
  AOI221XL g6284(.A0 (\fifo[1] [4]), .A1 (n_113), .B0 (n_116), .B1
       (\fifo[2] [4]), .C0 (n_182), .Y (n_198));
  AOI221XL g6285(.A0 (\fifo[8] [5]), .A1 (n_120), .B0 (n_106), .B1
       (\fifo[7] [5]), .C0 (n_176), .Y (n_197));
  AOI221XL g6286(.A0 (\fifo[8] [4]), .A1 (n_120), .B0 (n_106), .B1
       (\fifo[7] [4]), .C0 (n_180), .Y (n_196));
  AOI221XL g6287(.A0 (\fifo[1] [5]), .A1 (n_113), .B0 (n_116), .B1
       (\fifo[2] [5]), .C0 (n_178), .Y (n_195));
  AOI221XL g6289(.A0 (\fifo[12] [7]), .A1 (n_117), .B0 (n_114), .B1
       (\fifo[11] [7]), .C0 (n_170), .Y (n_194));
  AOI221XL g6290(.A0 (\fifo[12] [1]), .A1 (n_117), .B0 (n_114), .B1
       (\fifo[11] [1]), .C0 (n_173), .Y (n_193));
  AOI221XL g6291(.A0 (\fifo[4] [2]), .A1 (n_99), .B0 (n_111), .B1
       (\fifo[3] [2]), .C0 (n_174), .Y (n_192));
  AOI221XL g6292(.A0 (\fifo[12] [6]), .A1 (n_117), .B0 (n_114), .B1
       (\fifo[11] [6]), .C0 (n_177), .Y (n_191));
  AOI221XL g6293(.A0 (\fifo[1] [0]), .A1 (n_113), .B0 (n_116), .B1
       (\fifo[2] [0]), .C0 (n_185), .Y (n_190));
  AOI221XL g6294(.A0 (\fifo[13] [0]), .A1 (n_101), .B0 (n_103), .B1
       (\fifo[14] [0]), .C0 (n_181), .Y (n_189));
  AOI221XL g6295(.A0 (\fifo[0] [7]), .A1 (n_95), .B0 (n_62), .B1
       (data_out[7]), .C0 (n_172), .Y (n_188));
  AOI221XL g6296(.A0 (\fifo[12] [2]), .A1 (n_117), .B0 (n_114), .B1
       (\fifo[11] [2]), .C0 (n_171), .Y (n_187));
  AOI221XL g6297(.A0 (\fifo[4] [6]), .A1 (n_99), .B0 (n_111), .B1
       (\fifo[3] [6]), .C0 (n_175), .Y (n_186));
  OAI221XL g6298(.A0 (n_94), .A1 (n_50), .B0 (n_0), .B1 (n_45), .C0
       (n_164), .Y (n_185));
  OAI221XL g6299(.A0 (n_98), .A1 (n_35), .B0 (n_110), .B1 (n_30), .C0
       (n_167), .Y (n_184));
  OAI221XL g6300(.A0 (n_121), .A1 (n_32), .B0 (n_107), .B1 (n_7), .C0
       (n_166), .Y (n_183));
  OAI221XL g6301(.A0 (n_98), .A1 (n_41), .B0 (n_110), .B1 (n_42), .C0
       (n_169), .Y (n_182));
  OAI221XL g6302(.A0 (n_119), .A1 (n_10), .B0 (n_109), .B1 (n_37), .C0
       (n_165), .Y (n_181));
  OAI221XL g6303(.A0 (n_100), .A1 (n_15), .B0 (n_102), .B1 (n_18), .C0
       (n_163), .Y (n_180));
  OAI221XL g6304(.A0 (n_98), .A1 (n_8), .B0 (n_110), .B1 (n_13), .C0
       (n_162), .Y (n_179));
  OAI221XL g6305(.A0 (n_104), .A1 (n_39), .B0 (n_96), .B1 (n_19), .C0
       (n_157), .Y (n_178));
  OAI221XL g6306(.A0 (n_121), .A1 (n_21), .B0 (n_107), .B1 (n_12), .C0
       (n_161), .Y (n_177));
  OAI221XL g6307(.A0 (n_119), .A1 (n_11), .B0 (n_109), .B1 (n_22), .C0
       (n_159), .Y (n_176));
  OAI221XL g6308(.A0 (n_112), .A1 (n_25), .B0 (n_115), .B1 (n_6), .C0
       (n_158), .Y (n_175));
  OAI221XL g6309(.A0 (n_112), .A1 (n_38), .B0 (n_115), .B1 (n_26), .C0
       (n_156), .Y (n_174));
  OAI221XL g6310(.A0 (n_121), .A1 (n_34), .B0 (n_107), .B1 (n_17), .C0
       (n_160), .Y (n_173));
  OAI221XL g6311(.A0 (n_98), .A1 (n_5), .B0 (n_110), .B1 (n_16), .C0
       (n_155), .Y (n_172));
  OAI221XL g6312(.A0 (n_100), .A1 (n_24), .B0 (n_102), .B1 (n_31), .C0
       (n_168), .Y (n_171));
  OAI221XL g6313(.A0 (n_119), .A1 (n_20), .B0 (n_109), .B1 (n_9), .C0
       (n_154), .Y (n_170));
  AOI221XL g6314(.A0 (\fifo[5] [4]), .A1 (n_105), .B0 (n_97), .B1
       (\fifo[6] [4]), .C0 (n_153), .Y (n_169));
  AOI221XL g6315(.A0 (\fifo[8] [2]), .A1 (n_120), .B0 (n_106), .B1
       (\fifo[7] [2]), .C0 (n_149), .Y (n_168));
  AOI221XL g6316(.A0 (\fifo[5] [3]), .A1 (n_105), .B0 (n_97), .B1
       (\fifo[6] [3]), .C0 (n_152), .Y (n_167));
  AOI221XL g6317(.A0 (\fifo[9] [3]), .A1 (n_118), .B0 (n_108), .B1
       (\fifo[10] [3]), .C0 (n_150), .Y (n_166));
  AOI221XL g6318(.A0 (\fifo[8] [0]), .A1 (n_120), .B0 (n_106), .B1
       (\fifo[7] [0]), .C0 (n_151), .Y (n_165));
  AOI221XL g6319(.A0 (\fifo[4] [0]), .A1 (n_99), .B0 (n_111), .B1
       (\fifo[3] [0]), .C0 (n_146), .Y (n_164));
  AOI221XL g6320(.A0 (\fifo[9] [4]), .A1 (n_118), .B0 (n_108), .B1
       (\fifo[10] [4]), .C0 (n_148), .Y (n_163));
  AOI221XL g6321(.A0 (\fifo[5] [1]), .A1 (n_105), .B0 (n_97), .B1
       (\fifo[6] [1]), .C0 (n_147), .Y (n_162));
  AOI221XL g6386(.A0 (\fifo[9] [6]), .A1 (n_118), .B0 (n_108), .B1
       (\fifo[10] [6]), .C0 (n_145), .Y (n_161));
  AOI221XL g6387(.A0 (\fifo[9] [1]), .A1 (n_118), .B0 (n_108), .B1
       (\fifo[10] [1]), .C0 (n_143), .Y (n_160));
  AOI221XL g6388(.A0 (\fifo[12] [5]), .A1 (n_117), .B0 (n_114), .B1
       (\fifo[11] [5]), .C0 (n_144), .Y (n_159));
  AOI221XL g6389(.A0 (\fifo[5] [6]), .A1 (n_105), .B0 (n_97), .B1
       (\fifo[6] [6]), .C0 (n_142), .Y (n_158));
  AOI221XL g6390(.A0 (\fifo[4] [5]), .A1 (n_99), .B0 (n_111), .B1
       (\fifo[3] [5]), .C0 (n_141), .Y (n_157));
  AOI221XL g6391(.A0 (\fifo[5] [2]), .A1 (n_105), .B0 (n_97), .B1
       (\fifo[6] [2]), .C0 (n_140), .Y (n_156));
  AOI221XL g6392(.A0 (\fifo[1] [7]), .A1 (n_113), .B0 (n_116), .B1
       (\fifo[2] [7]), .C0 (n_139), .Y (n_155));
  AOI221XL g6393(.A0 (\fifo[8] [7]), .A1 (n_120), .B0 (n_106), .B1
       (\fifo[7] [7]), .C0 (n_138), .Y (n_154));
  AO22X1 g6459(.A0 (n_95), .A1 (\fifo[0] [4]), .B0 (n_62), .B1
       (data_out[4]), .Y (n_153));
  AO22X1 g6460(.A0 (n_95), .A1 (\fifo[0] [3]), .B0 (n_62), .B1
       (data_out[3]), .Y (n_152));
  AO22X1 g6461(.A0 (n_117), .A1 (\fifo[12] [0]), .B0 (n_114), .B1
       (\fifo[11] [0]), .Y (n_151));
  AO22X1 g6462(.A0 (n_117), .A1 (\fifo[12] [3]), .B0 (n_114), .B1
       (\fifo[11] [3]), .Y (n_150));
  AO22X1 g6463(.A0 (n_118), .A1 (\fifo[9] [2]), .B0 (n_108), .B1
       (\fifo[10] [2]), .Y (n_149));
  AO22X1 g6464(.A0 (n_117), .A1 (\fifo[12] [4]), .B0 (n_114), .B1
       (\fifo[11] [4]), .Y (n_148));
  AO22X1 g6465(.A0 (n_95), .A1 (\fifo[0] [1]), .B0 (n_62), .B1
       (data_out[1]), .Y (n_147));
  AO22X1 g6466(.A0 (n_105), .A1 (\fifo[5] [0]), .B0 (n_97), .B1
       (\fifo[6] [0]), .Y (n_146));
  AO22X1 g6467(.A0 (n_101), .A1 (\fifo[13] [6]), .B0 (n_103), .B1
       (\fifo[14] [6]), .Y (n_145));
  AO22X1 g6468(.A0 (n_101), .A1 (\fifo[13] [5]), .B0 (n_103), .B1
       (\fifo[14] [5]), .Y (n_144));
  AO22X1 g6469(.A0 (n_101), .A1 (\fifo[13] [1]), .B0 (n_103), .B1
       (\fifo[14] [1]), .Y (n_143));
  AO22X1 g6470(.A0 (n_95), .A1 (\fifo[0] [6]), .B0 (n_62), .B1
       (data_out[6]), .Y (n_142));
  AO22X1 g6471(.A0 (n_95), .A1 (\fifo[0] [5]), .B0 (n_62), .B1
       (data_out[5]), .Y (n_141));
  AO22X1 g6472(.A0 (n_95), .A1 (\fifo[0] [2]), .B0 (n_62), .B1
       (data_out[2]), .Y (n_140));
  AO22X1 g6473(.A0 (n_105), .A1 (\fifo[5] [7]), .B0 (n_97), .B1
       (\fifo[6] [7]), .Y (n_139));
  AO22X1 g6474(.A0 (n_101), .A1 (\fifo[13] [7]), .B0 (n_103), .B1
       (\fifo[14] [7]), .Y (n_138));
  NOR2BXL g6478(.AN (n_3), .B (n_88), .Y (n_137));
  NOR2BXL g6479(.AN (n_2), .B (n_91), .Y (n_136));
  NOR2BXL g6480(.AN (n_64), .B (n_91), .Y (n_135));
  NOR2BXL g6481(.AN (n_64), .B (n_90), .Y (n_134));
  NOR2BXL g6482(.AN (n_53), .B (n_90), .Y (n_133));
  NOR2BXL g6483(.AN (n_3), .B (n_92), .Y (n_132));
  NOR2BXL g6484(.AN (n_53), .B (n_91), .Y (n_131));
  NOR2BXL g6485(.AN (n_2), .B (n_92), .Y (n_130));
  NOR2BXL g6486(.AN (n_3), .B (n_90), .Y (n_129));
  NOR2BXL g6487(.AN (n_53), .B (n_88), .Y (n_128));
  NOR2BXL g6488(.AN (n_64), .B (n_88), .Y (n_127));
  NOR2BXL g6489(.AN (n_64), .B (n_92), .Y (n_126));
  NOR2BXL g6490(.AN (n_3), .B (n_91), .Y (n_125));
  NOR2BXL g6491(.AN (n_53), .B (n_92), .Y (n_124));
  NOR2BXL g6492(.AN (n_2), .B (n_88), .Y (n_123));
  CLKAND2X6 g6493(.A (n_2), .B (n_89), .Y (n_122));
  CLKINVX8 g6494(.A (n_121), .Y (n_120));
  CLKINVX8 g6495(.A (n_119), .Y (n_118));
  CLKINVX4 g6496(.A (n_116), .Y (n_115));
  CLKINVX4 g6497(.A (n_113), .Y (n_112));
  CLKINVX8 g6498(.A (n_110), .Y (n_111));
  CLKINVX8 g6499(.A (n_109), .Y (n_108));
  CLKINVX8 g6500(.A (n_107), .Y (n_106));
  CLKINVX4 g6501(.A (n_105), .Y (n_104));
  CLKINVX4 g6502(.A (n_103), .Y (n_102));
  CLKINVX4 g6503(.A (n_101), .Y (n_100));
  CLKINVX8 g6504(.A (n_98), .Y (n_99));
  CLKINVX4 g6505(.A (n_97), .Y (n_96));
  CLKINVX4 g6506(.A (n_95), .Y (n_94));
  OAI211XL g6510(.A0 (n_54), .A1 (n_70), .B0 (n_85), .C0 (n_60), .Y
       (n_121));
  OAI211XL g6511(.A0 (n_54), .A1 (n_59), .B0 (n_85), .C0 (n_67), .Y
       (n_119));
  AOI211XL g6512(.A0 (n_69), .A1 (n_53), .B0 (n_83), .C0 (n_61), .Y
       (n_117));
  AOI211XL g6513(.A0 (n_72), .A1 (n_64), .B0 (n_57), .C0 (n_81), .Y
       (n_116));
  AOI211XL g6514(.A0 (n_58), .A1 (n_64), .B0 (n_84), .C0 (n_66), .Y
       (n_114));
  AOI211XL g6515(.A0 (n_73), .A1 (n_2), .B0 (n_68), .C0 (n_81), .Y
       (n_113));
  OAI211XL g6516(.A0 (n_74), .A1 (n_63), .B0 (n_65), .C0 (n_80), .Y
       (n_110));
  OAI211XL g6517(.A0 (n_70), .A1 (n_63), .B0 (n_85), .C0 (n_56), .Y
       (n_109));
  OAI211XL g6518(.A0 (n_74), .A1 (n_55), .B0 (n_78), .C0 (n_65), .Y
       (n_107));
  AOI211XL g6519(.A0 (n_73), .A1 (n_53), .B0 (n_79), .C0 (n_68), .Y
       (n_105));
  AOI211XL g6520(.A0 (n_69), .A1 (n_3), .B0 (n_83), .C0 (n_57), .Y
       (n_103));
  AOI211XL g6521(.A0 (n_58), .A1 (n_53), .B0 (n_83), .C0 (n_68), .Y
       (n_101));
  OAI211XL g6522(.A0 (n_71), .A1 (n_52), .B0 (n_78), .C0 (n_60), .Y
       (n_98));
  AOI211XL g6523(.A0 (n_72), .A1 (n_3), .B0 (n_79), .C0 (n_57), .Y
       (n_97));
  AOI211XL g6524(.A0 (n_72), .A1 (n_2), .B0 (n_61), .C0 (n_81), .Y
       (n_95));
  OAI211XL g6525(.A0 (n_59), .A1 (n_55), .B0 (n_82), .C0 (n_65), .Y
       (n_93));
  NAND2BXL g6526(.AN (n_77), .B (w_ptr[3]), .Y (n_92));
  NAND2BXL g6527(.AN (n_86), .B (n_46), .Y (n_91));
  CLKINVX1 g6528(.A (n_89), .Y (n_90));
  XNOR2X1 g6529(.A (n_66), .B (r_ptr[2]), .Y (n_87));
  NOR3X4 g6530(.A (w_ptr[0]), .B (w_ptr[3]), .C (n_1), .Y (n_89));
  NAND2BXL g6531(.AN (n_86), .B (w_ptr[3]), .Y (n_88));
  CLKINVX3 g6532(.A (n_84), .Y (n_85));
  CLKINVX4 g6533(.A (n_83), .Y (n_82));
  NAND2BXL g6534(.AN (n_1), .B (w_ptr[0]), .Y (n_86));
  NAND2BXL g6535(.AN (n_75), .B (n_47), .Y (n_84));
  NAND2BXL g6536(.AN (n_75), .B (r_ptr[2]), .Y (n_83));
  CLKINVX3 g6537(.A (n_80), .Y (n_81));
  CLKINVX4 g6538(.A (n_79), .Y (n_78));
  OR2X1 g6539(.A (w_ptr[0]), .B (n_1), .Y (n_77));
  NAND2BXL g6540(.AN (n_66), .B (r_ptr[2]), .Y (n_76));
  NOR2BXL g6541(.AN (n_47), .B (n_4), .Y (n_80));
  NAND2BXL g6542(.AN (n_4), .B (r_ptr[2]), .Y (n_79));
  CLKINVX4 g6543(.A (n_74), .Y (n_73));
  CLKINVX3 g6544(.A (n_71), .Y (n_72));
  CLKINVX4 g6545(.A (n_70), .Y (n_69));
  CLKINVX4 g6546(.A (n_68), .Y (n_67));
  CLKINVX3 g6547(.A (n_66), .Y (n_65));
  CLKINVX4 g6548(.A (n_64), .Y (n_63));
  CLKINVX16 g6549(.A (n_0), .Y (n_62));
  NAND2BXL g6550(.AN (n_44), .B (r_en), .Y (n_75));
  NAND2BXL g6551(.AN (n_227), .B (n_46), .Y (n_74));
  NAND2BXL g6552(.AN (w_ptr[0]), .B (n_46), .Y (n_71));
  NAND2BXL g6553(.AN (w_ptr[0]), .B (w_ptr[3]), .Y (n_70));
  NAND2BXL g6554(.AN (r_ptr[1]), .B (r_ptr[0]), .Y (n_68));
  NAND2BXL g6555(.AN (n_48), .B (r_ptr[1]), .Y (n_66));
  NOR2BXL g6556(.AN (w_ptr[1]), .B (w_ptr[2]), .Y (n_64));
  CLKINVX4 g6558(.A (n_61), .Y (n_60));
  CLKINVX4 g6559(.A (n_59), .Y (n_58));
  CLKINVX4 g6560(.A (n_57), .Y (n_56));
  CLKINVX4 g6561(.A (n_3), .Y (n_55));
  CLKINVX4 g6562(.A (n_2), .Y (n_54));
  CLKINVX4 g6563(.A (n_53), .Y (n_52));
  CLKINVX2 g6564(.A (n_1), .Y (n_51));
  NAND2BXL g6566(.AN (r_ptr[0]), .B (n_43), .Y (n_61));
  NAND2BXL g6567(.AN (n_227), .B (w_ptr[3]), .Y (n_59));
  NAND2BXL g6568(.AN (r_ptr[0]), .B (r_ptr[1]), .Y (n_57));
  NOR2BXL g6571(.AN (w_ptr[2]), .B (w_ptr[1]), .Y (n_53));
  CLKINVX1 g6583(.A (\fifo[0] [0]), .Y (n_50));
  CLKINVX4 g6600(.A (r_ptr[0]), .Y (n_48));
  CLKINVX4 g6601(.A (r_ptr[2]), .Y (n_47));
  CLKINVX8 g6602(.A (w_ptr[3]), .Y (n_46));
  CLKINVX4 g6603(.A (data_out[0]), .Y (n_45));
  CLKINVX4 g6622(.A (r_ptr[3]), .Y (n_44));
  CLKINVX4 g6623(.A (r_ptr[1]), .Y (n_43));
  EDFFX2 \fifo_reg[1][2] (.CK (clk), .D (data_in[2]), .E (n_136), .Q
       (\fifo[1] [2]), .QN (n_38));
  EDFFX2 \fifo_reg[1][6] (.CK (clk), .D (data_in[6]), .E (n_136), .Q
       (\fifo[1] [6]), .QN (n_25));
  EDFFX2 \fifo_reg[2][2] (.CK (clk), .D (data_in[2]), .E (n_134), .Q
       (\fifo[2] [2]), .QN (n_26));
  EDFFX2 \fifo_reg[2][6] (.CK (clk), .D (data_in[6]), .E (n_134), .Q
       (\fifo[2] [6]), .QN (n_6));
  EDFFX2 \fifo_reg[3][1] (.CK (clk), .D (data_in[1]), .E (n_135), .Q
       (\fifo[3] [1]), .QN (n_13));
  EDFFX2 \fifo_reg[3][3] (.CK (clk), .D (data_in[3]), .E (n_135), .Q
       (\fifo[3] [3]), .QN (n_30));
  EDFFX2 \fifo_reg[3][4] (.CK (clk), .D (data_in[4]), .E (n_135), .Q
       (\fifo[3] [4]), .QN (n_42));
  EDFFX2 \fifo_reg[3][7] (.CK (clk), .D (data_in[7]), .E (n_135), .Q
       (\fifo[3] [7]), .QN (n_16));
  EDFFX2 \fifo_reg[4][1] (.CK (clk), .D (data_in[1]), .E (n_133), .Q
       (\fifo[4] [1]), .QN (n_8));
  EDFFX2 \fifo_reg[4][3] (.CK (clk), .D (data_in[3]), .E (n_133), .Q
       (\fifo[4] [3]), .QN (n_35));
  EDFFX2 \fifo_reg[4][4] (.CK (clk), .D (data_in[4]), .E (n_133), .Q
       (\fifo[4] [4]), .QN (n_41));
  EDFFX2 \fifo_reg[4][7] (.CK (clk), .D (data_in[7]), .E (n_133), .Q
       (\fifo[4] [7]), .QN (n_5));
  EDFFX2 \fifo_reg[5][5] (.CK (clk), .D (data_in[5]), .E (n_131), .Q
       (\fifo[5] [5]), .QN (n_39));
  EDFFX2 \fifo_reg[6][5] (.CK (clk), .D (data_in[5]), .E (n_129), .Q
       (\fifo[6] [5]), .QN (n_19));
  EDFFX2 \fifo_reg[7][1] (.CK (clk), .D (data_in[1]), .E (n_125), .Q
       (\fifo[7] [1]), .QN (n_17));
  EDFFX2 \fifo_reg[7][3] (.CK (clk), .D (data_in[3]), .E (n_125), .Q
       (\fifo[7] [3]), .QN (n_7));
  EDFFX2 \fifo_reg[7][6] (.CK (clk), .D (data_in[6]), .E (n_125), .Q
       (\fifo[7] [6]), .QN (n_12));
  EDFFX2 \fifo_reg[8][1] (.CK (clk), .D (data_in[1]), .E (n_130), .Q
       (\fifo[8] [1]), .QN (n_34));
  EDFFX2 \fifo_reg[8][3] (.CK (clk), .D (data_in[3]), .E (n_130), .Q
       (\fifo[8] [3]), .QN (n_32));
  EDFFX2 \fifo_reg[8][6] (.CK (clk), .D (data_in[6]), .E (n_130), .Q
       (\fifo[8] [6]), .QN (n_21));
  EDFFX2 \fifo_reg[9][0] (.CK (clk), .D (data_in[0]), .E (n_123), .Q
       (\fifo[9] [0]), .QN (n_10));
  EDFFX2 \fifo_reg[9][5] (.CK (clk), .D (data_in[5]), .E (n_123), .Q
       (\fifo[9] [5]), .QN (n_11));
  EDFFX2 \fifo_reg[9][7] (.CK (clk), .D (data_in[7]), .E (n_123), .Q
       (\fifo[9] [7]), .QN (n_20));
  EDFFX2 \fifo_reg[10][0] (.CK (clk), .D (data_in[0]), .E (n_126), .Q
       (\fifo[10] [0]), .QN (n_37));
  EDFFX2 \fifo_reg[10][5] (.CK (clk), .D (data_in[5]), .E (n_126), .Q
       (\fifo[10] [5]), .QN (n_22));
  EDFFX2 \fifo_reg[10][7] (.CK (clk), .D (data_in[7]), .E (n_126), .Q
       (\fifo[10] [7]), .QN (n_9));
  EDFFX2 \fifo_reg[13][2] (.CK (clk), .D (data_in[2]), .E (n_128), .Q
       (\fifo[13] [2]), .QN (n_24));
  EDFFX2 \fifo_reg[13][4] (.CK (clk), .D (data_in[4]), .E (n_128), .Q
       (\fifo[13] [4]), .QN (n_15));
  EDFFX2 \fifo_reg[14][2] (.CK (clk), .D (data_in[2]), .E (n_132), .Q
       (\fifo[14] [2]), .QN (n_31));
  EDFFX2 \fifo_reg[14][4] (.CK (clk), .D (data_in[4]), .E (n_132), .Q
       (\fifo[14] [4]), .QN (n_18));
  EDFFX2 \fifo_reg[15][0] (.CK (clk), .D (data_in[0]), .E (n_137), .Q
       (\fifo[15] [0]), .QN (n_14));
  EDFFX2 \fifo_reg[15][1] (.CK (clk), .D (data_in[1]), .E (n_137), .Q
       (\fifo[15] [1]), .QN (n_28));
  EDFFX2 \fifo_reg[15][2] (.CK (clk), .D (data_in[2]), .E (n_137), .Q
       (\fifo[15] [2]), .QN (n_23));
  EDFFX2 \fifo_reg[15][3] (.CK (clk), .D (data_in[3]), .E (n_137), .Q
       (\fifo[15] [3]), .QN (n_27));
  EDFFX2 \fifo_reg[15][4] (.CK (clk), .D (data_in[4]), .E (n_137), .Q
       (\fifo[15] [4]), .QN (n_33));
  EDFFX2 \fifo_reg[15][5] (.CK (clk), .D (data_in[5]), .E (n_137), .Q
       (\fifo[15] [5]), .QN (n_36));
  EDFFX2 \fifo_reg[15][6] (.CK (clk), .D (data_in[6]), .E (n_137), .Q
       (\fifo[15] [6]), .QN (n_29));
  EDFFX2 \fifo_reg[15][7] (.CK (clk), .D (data_in[7]), .E (n_137), .Q
       (\fifo[15] [7]), .QN (n_40));
  NAND2BX4 g1445(.AN (r_ptr[3]), .B (r_en), .Y (n_4));
  CLKAND2X12 g6700(.A (w_ptr[2]), .B (w_ptr[1]), .Y (n_3));
  NOR2X8 g6701(.A (w_ptr[2]), .B (w_ptr[1]), .Y (n_2));
  NAND2BX4 g6702(.AN (full), .B (w_en), .Y (n_1));
  AND2X8 g6703(.A (r_en), .B (n_230), .Y (n_0));
endmodule

